"""baseline schema from models

Revision ID: 31d43b7e01c0
Revises:
Create Date: 2026-07-20 11:31:41.488831

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "31d43b7e01c0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "id_schemes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("validator", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_id_schemes_code"), "id_schemes", ["code"], unique=True)
    op.create_table(
        "jobs",
        sa.Column("job_key", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("job_key"),
    )
    op.create_table(
        "run_logs_v2",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("worker_name", sa.Text(), nullable=False),
        sa.Column("worker_type", sa.Text(), nullable=False),
        sa.Column(
            "transform_type",
            sa.Enum(
                "extract_audio",
                "test",
                "transcribe",
                "transcode",
                "youtube",
                "whisper_ingest",
                "clipper",
                "stream_reader",
                "ffprobe_metadata",
                name="transform_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("running_time", sa.Integer(), nullable=False),
        sa.Column("extras", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runner_state",
        sa.Column("runner_key", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("runner_key"),
    )
    op.create_table(
        "scanner_run_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("worker_name", sa.Text(), nullable=False),
        sa.Column("worker_type", sa.Text(), nullable=False),
        sa.Column("scan_path", sa.Text(), nullable=False),
        sa.Column("relative_to_path", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("running_time", sa.Integer(), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("processed_count", sa.Integer(), nullable=False),
        sa.Column("folder_count", sa.Integer(), nullable=False),
        sa.Column("excluded_count", sa.Integer(), nullable=False),
        sa.Column("previously_seen_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("api_error_count", sa.Integer(), nullable=False),
        sa.Column("no_metadata_count", sa.Integer(), nullable=False),
        sa.Column("unsupported_file_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["tags.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=True)
    op.create_index("ix_tags_parent_id", "tags", ["parent_id"], unique=False)
    op.create_table(
        "titles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "title_type",
            sa.Enum(
                "movie",
                "tv",
                "music",
                "audiobook",
                "event",
                "collection",
                "season",
                "other",
                name="title_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column("synopsis", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "videos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("duration", sa.Numeric(), nullable=False),
        sa.Column("bitrate", sa.BigInteger(), nullable=False),
        sa.Column("container_format", sa.Text(), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("mtime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("master_asset_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("bitrate >= 0", name="ck_asset_valid_bitrate"),
        sa.CheckConstraint("duration >= 0", name="ck_asset_valid_duration"),
        sa.CheckConstraint(
            "master_asset_id IS NULL OR master_asset_id <> id", name="ck_asset_not_own_master"
        ),
        sa.CheckConstraint("size >= 0", name="ck_asset_valid_size"),
        sa.ForeignKeyConstraint(["master_asset_id"], ["videos.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_index(op.f("ix_videos_master_asset_id"), "videos", ["master_asset_id"], unique=False)
    op.create_table(
        "asset_tags",
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["videos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("asset_id", "tag_id"),
    )
    op.create_index("ix_asset_tags_asset_id", "asset_tags", ["asset_id"], unique=False)
    op.create_index("ix_asset_tags_tag_id", "asset_tags", ["tag_id"], unique=False)
    op.create_table(
        "external_asset_ids",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("scheme_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["videos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scheme_id"], ["id_schemes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "scheme_id", name="uq_asset_scheme"),
        sa.UniqueConstraint("scheme_id", "external_id", name="uq_scheme_external_id"),
    )
    op.create_table(
        "external_identifiers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scheme_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum("asset", "title", name="entity_type_enum", create_constraint=True),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scheme_id"], ["id_schemes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scheme_id", "external_id", name="uq_external_identifier_scheme_id"),
    )
    op.create_table(
        "media_transform_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column(
            "transform_type",
            sa.Enum(
                "extract_audio",
                "test",
                "transcribe",
                "transcode",
                "youtube",
                "whisper_ingest",
                "clipper",
                "stream_reader",
                "ffprobe_metadata",
                name="transform_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("parameters", sa.JSON(), nullable=True),
        sa.Column("actioned", sa.Boolean(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("worker_notes", sa.Text(), nullable=True),
        sa.Column("duration", sa.Numeric(), nullable=True),
        sa.Column("flow_run_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum("cancelled", "succeeded", "failed", name="outcome_enum"),
            nullable=True,
        ),
        sa.Column("worker", sa.Text(), nullable=True),
        sa.Column("parent_transform_request_id", sa.Integer(), nullable=True),
        sa.Column("on_success", sa.JSON(), nullable=True),
        sa.Column("on_failure", sa.JSON(), nullable=True),
        sa.Column("first_heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "((actioned = true) AND (processed_at IS NOT NULL) AND (outcome IS NOT NULL)) OR ((actioned = false) AND (processed_at IS NULL) AND (outcome IS NULL))",
            name="check_processed_at_matches_actioned",
        ),
        sa.ForeignKeyConstraint(
            ["parent_transform_request_id"], ["media_transform_requests.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uniq_pending_transform_per_video_and_type",
        "media_transform_requests",
        ["video_id", "transform_type"],
        unique=True,
        postgresql_where=sa.text("(actioned = false)"),
        sqlite_where=sa.text("(actioned = 0)"),
    )
    op.create_table(
        "metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("metadata_type", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "streams",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("stream_index", sa.Integer(), nullable=True),
        sa.Column("codec_type", sa.Text(), nullable=False),
        sa.Column("codec_name", sa.Text(), nullable=True),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("frame_rate", sa.Numeric(), nullable=True),
        sa.Column("channels", sa.Integer(), nullable=True),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("is_forced", sa.Boolean(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "title_contents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_title_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Enum("asset", "title", name="content_kind"), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=True),
        sa.Column("child_title_id", sa.Integer(), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column(
            "order_key",
            sa.Text().with_variant(sa.TEXT(collation="C"), "postgresql"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(  (kind = 'asset' AND asset_id IS NOT NULL AND child_title_id IS NULL)  OR  (kind = 'title' AND child_title_id IS NOT NULL AND asset_id IS NULL))",
            name="one_target_chk",
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["videos.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["child_title_id"], ["titles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["parent_title_id"], ["titles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parent_title_id", "order_key", name="uq_parent_order"),
    )
    op.create_index(
        "uq_parent_asset_once",
        "title_contents",
        ["parent_title_id", "asset_id"],
        unique=True,
        postgresql_where=sa.text("asset_id IS NOT NULL"),
    )
    op.create_index(
        "uq_parent_child_title_once",
        "title_contents",
        ["parent_title_id", "child_title_id"],
        unique=True,
        postgresql_where=sa.text("child_title_id IS NOT NULL"),
    )
    op.create_table(
        "title_references",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column(
            "reference_type",
            sa.Enum(
                "review",
                "metadata",
                "article",
                "summary",
                "other",
                name="title_reference_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("reference_url", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["title_id"], ["titles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "title_tags",
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["title_id"], ["titles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("title_id", "tag_id"),
    )
    op.create_index("ix_title_tags_tag_id", "title_tags", ["tag_id"], unique=False)
    op.create_index("ix_title_tags_title_id", "title_tags", ["title_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_title_tags_title_id", table_name="title_tags")
    op.drop_index("ix_title_tags_tag_id", table_name="title_tags")
    op.drop_table("title_tags")
    op.drop_table("title_references")
    op.drop_index(
        "uq_parent_child_title_once",
        table_name="title_contents",
        postgresql_where=sa.text("child_title_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_parent_asset_once",
        table_name="title_contents",
        postgresql_where=sa.text("asset_id IS NOT NULL"),
    )
    op.drop_table("title_contents")
    op.drop_table("streams")
    op.drop_table("metadata")
    op.drop_index(
        "uniq_pending_transform_per_video_and_type",
        table_name="media_transform_requests",
        postgresql_where=sa.text("(actioned = false)"),
        sqlite_where=sa.text("(actioned = 0)"),
    )
    op.drop_table("media_transform_requests")
    op.drop_table("external_identifiers")
    op.drop_table("external_asset_ids")
    op.drop_index("ix_asset_tags_tag_id", table_name="asset_tags")
    op.drop_index("ix_asset_tags_asset_id", table_name="asset_tags")
    op.drop_table("asset_tags")
    op.drop_index(op.f("ix_videos_master_asset_id"), table_name="videos")
    op.drop_table("videos")
    op.drop_table("titles")
    op.drop_index("ix_tags_parent_id", table_name="tags")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_table("tags")
    op.drop_table("scanner_run_logs")
    op.drop_table("runner_state")
    op.drop_table("run_logs_v2")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_id_schemes_code"), table_name="id_schemes")
    op.drop_table("id_schemes")
    # ### end Alembic commands ###
