"""add library_root to titles

Whether a title belongs in the library grid is not the same question as whether it can
be played. `type` carries watchability -- a standalone film is both root and watchable,
a series is root but not watchable, an episode is watchable but not root, and a season
is neither -- so rootness needs a column of its own (#91).

Stored rather than derived. Parent absence is the closest structural proxy and is still
wrong: a curated collection has no parent and is not a library root. Deriving it would
also put an anti-join against `title_contents` in the query the grid issues on every
load, which is the one query in this application that must not acquire one.

Hand-written rather than autogenerated: the backfill and its report are data changes
autogenerate cannot produce.

Revision ID: 4f8b21c7ae60
Revises: 7c4a1e9d2b83
Create Date: 2026-08-29 09:15:00.000000

"""

import logging
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f8b21c7ae60"
down_revision: Union[str, Sequence[str], None] = "7c4a1e9d2b83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_INDEX = "ix_titles_library_root_id"

#: Title types that are never a library root, whatever their containment says.
#:
#: A collection exists to list things and is reached from the list surface, not the
#: grid. A season is not an entry point in its own right -- you arrive at one through
#: its series. Named as literals rather than imported from ``DEFAULT_TITLE_TYPES``: a
#: migration records what was true when it ran.
_NEVER_ROOT_TYPE_CODES = ("collection", "season")

logger = logging.getLogger("alembic.runtime.migration")


def upgrade() -> None:
    """Add the column, apply the backfill rule, then report what it could not decide."""
    bind = op.get_bind()

    op.add_column(
        "titles",
        sa.Column("library_root", sa.Boolean(), nullable=False, server_default="false"),
    )

    # The rule: a title is a library root when nothing intrinsically contains it and its
    # type is one that can be an entry point.
    #
    # Intrinsic is what makes this expressible at all (#90). Before that column existed
    # a curated listing was indistinguishable from a home, so "has no parent" would have
    # excluded every title that appears in any list.
    promoted = bind.execute(
        sa.text(
            "UPDATE titles SET library_root = true "
            "WHERE NOT EXISTS ("
            "  SELECT 1 FROM title_contents tc"
            "  WHERE tc.child_title_id = titles.id AND tc.membership = 'intrinsic'"
            ") "
            "AND title_type_id NOT IN (SELECT id FROM title_types WHERE code = ANY(:codes))"
        ),
        {"codes": list(_NEVER_ROOT_TYPE_CODES)},
    ).rowcount
    total = bind.execute(sa.text("SELECT count(*) FROM titles")).scalar_one()
    logger.info("Marked %s of %s title(s) as library roots", promoted, total)

    # What the rule could not decide, rather than what it decided.
    #
    # A season with no intrinsic parent is the case the rule handles by fiat: the type
    # exclusion makes it not-root, but structurally it is an orphan whose series is
    # missing, and "not a library root" may not be the right answer for it. Logged
    # individually because each one is a data problem someone has to look at, not a
    # number to note.
    orphaned = bind.execute(
        sa.text(
            "SELECT t.id, t.name FROM titles t "
            "JOIN title_types tt ON tt.id = t.title_type_id "
            "WHERE tt.code = 'season' AND NOT EXISTS ("
            "  SELECT 1 FROM title_contents tc"
            "  WHERE tc.child_title_id = t.id AND tc.membership = 'intrinsic'"
            ")"
        )
    ).fetchall()
    for title_id, name in orphaned:
        logger.warning(
            "Unclassifiable: season %s (%r) has no series containing it. Left not-root "
            "by the type rule; confirm whether it is an entry point.",
            title_id,
            name,
        )

    # The rule's other judgement call, which is defensible but worth counting: a title
    # that appears only in curated lists has no home, and the rule calls it a root. That
    # is right for a standalone film someone has added to a list, and wrong for anything
    # whose series edge was never created.
    listed_only = bind.execute(
        sa.text(
            "SELECT count(*) FROM titles t "
            "WHERE EXISTS ("
            "  SELECT 1 FROM title_contents tc"
            "  WHERE tc.child_title_id = t.id AND tc.membership = 'curated'"
            ") AND NOT EXISTS ("
            "  SELECT 1 FROM title_contents tc"
            "  WHERE tc.child_title_id = t.id AND tc.membership = 'intrinsic'"
            ")"
        )
    ).scalar_one()
    if listed_only:
        logger.info(
            "%s title(s) appear only in curated lists and were marked roots; correct for "
            "a standalone title someone has listed, wrong for one missing its home edge",
            listed_only,
        )

    # Created after the backfill so it is built once over final values rather than
    # maintained through the UPDATE.
    #
    # Composite rather than a bare boolean. Roots are the majority of this table, and at
    # that selectivity the planner is right to ignore an index on the flag alone -- it
    # would be declared "index-covered" and sequential-scanned in practice, which this
    # repository has shipped four times already (#50, #53, #58, #59). Including `id`,
    # which is both the default sort and the tiebreaker keyset pagination always
    # appends, is what makes the index usable: it turns the grid's
    # `WHERE library_root ORDER BY id LIMIT n` into an ordered scan that stops at the
    # page boundary instead of sorting every root. Verified with EXPLAIN against a
    # populated table, not only with the inventory harness.
    op.create_index(_INDEX, "titles", ["library_root", "id"])


def downgrade() -> None:
    """Drop the index and the column.

    Lossy: the classification is discarded, including any hand-corrections made since
    the backfill. Re-running the upgrade reapplies the rule, not those corrections.
    """
    op.drop_index(_INDEX, table_name="titles")
    op.drop_column("titles", "library_root")
