"""add membership to title_contents

Distinguishes intrinsic containment (a Series contains a Season contains an Episode --
an item's home, which drives breadcrumbs) from curated containment (a list that
mentions items living elsewhere). The two are structurally identical without this
column, so nothing could tell a breadcrumb edge from a listing (#90).

Hand-written rather than autogenerated. Alembic does not compare partial index
predicates, and the backfill and its ambiguity report are data changes autogenerate
cannot produce at all. The matching column and index on ``TitleContentORM`` are what
the test suite's ``create_all`` builds from; the two are kept in step by hand.

The column is NOT NULL DEFAULT 'intrinsic' rather than nullable because rows arrive in
this table from a producer that does not use the API -- see 178b5739d95f, whose 263
self-containment rows came that way from something still running. That writer will keep
inserting without naming this column, and the default is what keeps its rows correct.

Revision ID: 7c4a1e9d2b83
Revises: 178b5739d95f
Create Date: 2026-08-28 23:40:00.000000

"""

import logging
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7c4a1e9d2b83"
down_revision: Union[str, Sequence[str], None] = "178b5739d95f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_ENUM_NAME = "membership_kind"
_ENUM_LABELS = ("intrinsic", "curated")
_INDEX = "uq_one_intrinsic_parent"

#: The title type whose contents are a curated list rather than a containment tree.
#: Seeded in ``DEFAULT_TITLE_TYPES``, and named as a literal here rather than imported:
#: a migration records what was true when it ran and must not change meaning when the
#: application's copy of that list moves on.
_CURATED_PARENT_TYPE_CODE = "collection"

logger = logging.getLogger("alembic.runtime.migration")


def upgrade() -> None:
    """Add the column, classify the existing rows, then enforce one home per title."""
    bind = op.get_bind()

    membership = postgresql.ENUM(*_ENUM_LABELS, name=_ENUM_NAME, create_type=False)
    membership.create(bind, checkfirst=True)

    op.add_column(
        "title_contents",
        sa.Column(
            "membership",
            membership,
            nullable=False,
            server_default="intrinsic",
        ),
    )

    # Backfill rule: everything is a home except what hangs off a collection.
    #
    # Every edge starts intrinsic by virtue of the default, which is right for all but
    # one identifiable case -- a parent that exists to list things rather than to
    # contain them. `collection` is the only title type in the seeded vocabulary that
    # means that.
    #
    # Expected to affect zero rows on the production database as of writing, where no
    # curated list has been built yet. That is the reason to log the count rather than
    # assume it: a backfill that reports nothing leaves no way to tell "there were
    # none" from "it did not run".
    curated = bind.execute(
        sa.text(
            "UPDATE title_contents SET membership = 'curated' "
            "WHERE parent_title_id IN ("
            "  SELECT t.id FROM titles t"
            "  JOIN title_types tt ON tt.id = t.title_type_id"
            "  WHERE tt.code = :code"
            ")"
        ),
        {"code": _CURATED_PARENT_TYPE_CODE},
    ).rowcount
    logger.info(
        "Classified %s title_contents row(s) as curated (parent type %r); the rest are intrinsic",
        curated,
        _CURATED_PARENT_TYPE_CODE,
    )

    # The ambiguous case, and the only one this migration cannot decide correctly.
    #
    # A child left with two intrinsic parents has two homes, and nothing in the data
    # says which one a breadcrumb should follow. Demoting the later edge to curated is
    # the one repair that loses no rows: the membership is recoverable by hand, whereas
    # a deleted edge is not. Lowest id wins on the grounds that the earliest recorded
    # containment is the likeliest home -- a tiebreak, not a fact, which is why each one
    # is logged individually rather than counted.
    #
    # Expected to be empty: every title that has a parent has exactly one, once
    # 178b5739d95f removed the self-edges that made it look otherwise.
    demoted = bind.execute(
        sa.text(
            "WITH ranked AS ("
            "  SELECT id, child_title_id,"
            "         ROW_NUMBER() OVER (PARTITION BY child_title_id ORDER BY id) AS rn"
            "  FROM title_contents"
            "  WHERE child_title_id IS NOT NULL AND membership = 'intrinsic'"
            ")"
            "UPDATE title_contents tc SET membership = 'curated' "
            "FROM ranked r WHERE tc.id = r.id AND r.rn > 1 "
            "RETURNING tc.id, tc.child_title_id"
        )
    ).fetchall()
    for row_id, child_title_id in demoted:
        logger.warning(
            "Ambiguous containment: title %s had more than one intrinsic parent; "
            "demoted containment row %s to curated. Review which parent is its home.",
            child_title_id,
            row_id,
        )
    logger.info("Demoted %s ambiguous intrinsic edge(s) to curated", len(demoted))

    # Created last, because it can only be added once the data above satisfies it.
    op.create_index(
        _INDEX,
        "title_contents",
        ["child_title_id"],
        unique=True,
        postgresql_where=sa.text("child_title_id IS NOT NULL AND membership = 'intrinsic'"),
    )


def downgrade() -> None:
    """Drop the index, the column, and the type.

    Lossy in one direction only: the intrinsic/curated classification is discarded,
    including any edge this migration demoted. The edges themselves are untouched, so
    the containment graph is unchanged -- what is lost is the ability to tell which
    edges were which.
    """
    op.drop_index(_INDEX, table_name="title_contents")
    op.drop_column("title_contents", "membership")
    postgresql.ENUM(name=_ENUM_NAME, create_type=False).drop(op.get_bind(), checkfirst=True)
