# app/repositories/protocols.py
from collections.abc import Sequence
from pathlib import Path
from typing import Protocol

from app.schemas import (
    ArtworkCreateInternal,
    ArtworkKindCreateInternal,
    ArtworkKindRead,
    ArtworkKindUpdateInternal,
    ArtworkListParams,
    ArtworkRead,
    ArtworkUpdateInternal,
    AssetCreateInternal,
    AssetListParams,
    AssetRead,
    AssetReadExtended,
    AssetUpdateInternal,
    ExternalIdentifierCreateInternal,
    ExternalIdentifierRead,
    ExternalIdentifierReadExtended,
    ExternalIdentifierUpdateInternal,
    IdSchemeCreateInternal,
    IdSchemeRead,
    IdSchemeUpdateInternal,
    InboxDeleteRequest,
    InboxImportRequest,
    InboxItem,
    MetadataCreateInternal,
    MetadataRead,
    MetadataUpdateInternal,
    PaginatedResponse,
    RunnerStateCreateInternal,
    RunnerStateRead,
    RunnerStateUpdateInternal,
    RunSummaryCreateInternal,
    RunSummaryRead,
    ScannerRunSummaryCreateInternal,
    ScannerRunSummaryRead,
    StreamCreateInternal,
    StreamListParams,
    StreamRead,
    StreamUpdateInternal,
    TagCounts,
    TagCreateInternal,
    TagListParams,
    TagRead,
    TagUpdateInternal,
    TitleContentCounts,
    TitleContentCreateInternal,
    TitleContentInsert,
    TitleContentRead,
    TitleContentReadExtended,
    TitleContentReadParent,
    TitleContentUpdateInternal,
    TitleCreateInternal,
    TitleListParams,
    TitleMediaTotals,
    TitleRead,
    TitleReadExtended,
    TitleReferenceCreateInternal,
    TitleReferenceRead,
    TitleReferenceUpdateInternal,
    TitleTypeCreateInternal,
    TitleTypeRead,
    TitleTypeUpdateInternal,
    TitleUpdateInternal,
    TransformRequestCreateInternal,
    TransformRequestListParams,
    TransformRequestRead,
    TransformRequestReadExpanded,
    TransformRequestUpdateInternal,
)
from app.schemas.enums import EntityTypeEnum
from app.schemas.job import JobRead


class MediaRepository(Protocol):
    def create(self, asset: AssetCreateInternal) -> AssetRead: ...
    def get(self, asset_id: int, with_master_asset: bool = True) -> AssetReadExtended | None: ...
    def get_by_external_id(self, scheme_id: int, external_id: str) -> AssetRead | None: ...
    def exists(self, asset_id: int) -> bool: ...
    def path_exists(self, path: str, exclude_asset_id: int | None = None) -> bool: ...
    def list_paged(self, params: AssetListParams) -> PaginatedResponse[AssetReadExtended]: ...
    def list_derived_assets(self, asset_id: int) -> list[AssetRead]: ...
    def update(self, asset_id: int, update: AssetUpdateInternal) -> AssetRead: ...  # type: ignore
    def mark_assets_seen(self, ids: list[int]) -> int: ...


class RunnerStateRepository(Protocol):
    def get_runner_state(self, runner_key: str) -> RunnerStateRead | None: ...
    def create(self, state: RunnerStateCreateInternal) -> RunnerStateRead: ...
    def set_runner_state(
        self, runner_key: str, update: RunnerStateUpdateInternal
    ) -> RunnerStateRead: ...


class StreamRepository(Protocol):
    def create(self, stream: StreamCreateInternal) -> StreamRead: ...
    def get(self, stream_id: int) -> StreamRead | None: ...
    def exists(self, stream_id: int) -> bool: ...
    def list_paged(self, params: StreamListParams) -> PaginatedResponse[StreamRead]: ...
    def update(self, stream_id: int, update: StreamUpdateInternal) -> StreamRead: ...  # type: ignore
    def get_asset_streams(self, asset_id: int) -> list[StreamRead]: ...
    def delete_asset_streams(self, asset_id: int) -> None: ...


class RunSummaryRepository(Protocol):
    def create(self, run_summary: RunSummaryCreateInternal) -> RunSummaryRead: ...
    def get(self, run_summary_id: int) -> RunSummaryRead | None: ...
    def exists(self, run_summary_id: int) -> bool: ...


class ScannerRunSummaryRepository(Protocol):
    def create(self, run_summary: ScannerRunSummaryCreateInternal) -> ScannerRunSummaryRead: ...
    def get(self, run_summary_id: int) -> ScannerRunSummaryRead | None: ...
    def exists(self, run_summary_id: int) -> bool: ...


class TitleRepository(Protocol):
    def create(self, title: TitleCreateInternal) -> TitleRead: ...
    def get(self, title_id: int) -> TitleRead | None: ...
    def get_by_external_id(self, scheme_id: int, external_id: str) -> TitleRead | None: ...
    def exists(self, title_id: int) -> bool: ...
    def list_paged(
        self,
        params: TitleListParams,
        display_image_kind_ids: Sequence[int] | None = None,
    ) -> PaginatedResponse[TitleReadExtended]: ...
    def update(self, title_id: int, update: TitleUpdateInternal) -> TitleRead: ...  # type: ignore


class TitleTypeRepository(Protocol):
    def create(self, title_type: TitleTypeCreateInternal) -> TitleTypeRead: ...
    def get(self, title_type_id: int) -> TitleTypeRead | None: ...
    def exists(self, title_type_id: int) -> bool: ...
    def get_by_code(self, code: str) -> TitleTypeRead | None: ...
    def list_all(self) -> list[TitleTypeRead]: ...
    def update(
        self,
        title_type_id: int,
        update: TitleTypeUpdateInternal,  # type: ignore
    ) -> TitleTypeRead: ...
    def delete(self, title_type_id: int) -> None: ...
    def usage_count(self, title_type_id: int) -> int: ...


class TitleReferenceRepository(Protocol):
    def create(self, title_reference: TitleReferenceCreateInternal) -> TitleReferenceRead: ...
    def get(self, title_reference_id: int) -> TitleReferenceRead | None: ...
    def exists(self, title_reference_id: int) -> bool: ...
    def list_title_references(self, title_id: int) -> list[TitleReferenceRead]: ...
    def update(
        self,
        title_reference_id: int,
        update: TitleReferenceUpdateInternal,  # type: ignore
    ) -> TitleReferenceRead: ...


class TitleContentRepository(Protocol):
    def can_reach(
        self, start_title_id: int, target_title_id: int, max_depth: int = ...
    ) -> bool: ...
    def counts_for_titles(self, title_ids: Sequence[int]) -> dict[int, TitleContentCounts]: ...
    def totals_for_titles(
        self, title_ids: Sequence[int], max_depth: int = ...
    ) -> dict[int, TitleMediaTotals]: ...
    def create(self, title_content: TitleContentCreateInternal) -> TitleContentRead: ...
    def get(self, title_content_id: int) -> TitleContentRead | None: ...
    def exists(self, title_content_id: int) -> bool: ...
    def list_title_content(
        self, parent_title_id: int, include_children: bool = False
    ) -> list[TitleContentReadExtended]: ...
    def update(
        self,
        title_content_id: int,
        update: TitleContentUpdateInternal,  # type: ignore
    ) -> TitleContentRead: ...
    def delete_title_content(self, title_content_id: int) -> None: ...
    def get_titles_with_asset(self, asset_id: int) -> list[TitleContentReadParent]: ...
    def get_parents_of_title(self, title_id: int) -> list[TitleContentReadParent]: ...
    def intrinsic_parent_edge_id(self, child_title_id: int) -> int | None: ...

    # Ordering. `anchor` is "start" or "end"; it is named that rather than `position`
    # so it cannot be read as the integer column of the same name.
    def reorder(
        self,
        parent_title_id: int,
        title_content_id: int,
        *,
        before_id: int | None = None,
        after_id: int | None = None,
        anchor: str | None = None,
    ) -> TitleContentRead | None: ...

    def create_positioned(
        self,
        parent_title_id: int,
        title_content: TitleContentInsert,
        *,
        before_id: int | None = None,
        after_id: int | None = None,
        anchor: str | None = None,
    ) -> TitleContentRead | None: ...

    # Batch writes (#179). Each applies as one transaction under one set of parent
    # locks; the service validates every item before calling them, so these do not
    # re-check what a single write's service path checks.
    def create_many_positioned(
        self, parent_title_id: int, inserts: Sequence[TitleContentInsert]
    ) -> list[TitleContentRead]: ...

    def delete_many(self, parent_title_id: int, title_content_ids: Sequence[int]) -> int: ...

    def move_many(
        self, destination_title_id: int, title_content_ids: Sequence[int]
    ) -> list[TitleContentRead]: ...


class TransformRequestRepository(Protocol):
    def create(self, request: TransformRequestCreateInternal) -> TransformRequestRead: ...
    def get(self, request_id: int) -> TransformRequestRead | None: ...
    def exists(self, request_id: int) -> bool: ...
    def list_paged(
        self, params: TransformRequestListParams
    ) -> PaginatedResponse[TransformRequestReadExpanded]: ...
    def update(
        self,
        request_id: int,
        update: TransformRequestUpdateInternal,  # type: ignore
    ) -> TransformRequestRead: ...
    def get_asset_transform_requests(self, asset_id: int) -> list[TransformRequestRead]: ...
    def claim_next(
        self, transform_type: str, worker: str, external_job_id: str | None
    ) -> TransformRequestReadExpanded: ...
    def mark_heartbeat(self, request_id: int) -> None: ...


class TagRepository(Protocol):
    def create(self, tag: TagCreateInternal) -> TagRead: ...
    def exists(self, tag_id: int) -> bool: ...
    def get(self, tag_id: int) -> TagRead | None: ...
    def get_by_name(self, name: str) -> TagRead | None: ...
    def get_by_names(self, names: list[str]) -> list[TagRead]: ...
    def get_or_create_by_names(self, names: list[str]) -> list[TagRead]: ...
    def update(self, tag_id: int, update: TagUpdateInternal) -> TagRead: ...  # type: ignore
    def list_tags(self, parent_id: int | None = None) -> list[TagRead]: ...
    def list_paged(
        self, params: TagListParams, parent_id: int | None
    ) -> PaginatedResponse[TagRead]: ...

    # Asset tagging
    def add_asset_tags(self, asset_id: int, tag_ids: list[int]) -> list[TagRead]: ...
    def remove_asset_tag(self, asset_id: int, tag_id: int) -> bool: ...
    def remove_all_asset_tags(self, asset_id: int) -> int: ...
    def get_asset_tags(self, asset_id: int) -> list[TagRead]: ...

    # Title tagging
    def add_title_tags(self, title_id: int, tag_ids: list[int]) -> list[TagRead]: ...
    def remove_title_tag(self, title_id: int, tag_id: int) -> bool: ...
    def remove_all_title_tags(self, title_id: int) -> int: ...
    def get_title_tags(self, title_id: int) -> list[TagRead]: ...

    # Counting
    def count_tag_assets(self, tag_id: int) -> int: ...
    def count_tag_titles(self, tag_id: int) -> int: ...
    def get_tag_usage_stats(self, tag_id: int) -> TagCounts: ...


class IdSchemeRepository(Protocol):
    def create(self, scheme: IdSchemeCreateInternal) -> IdSchemeRead: ...
    def get(self, scheme_id: int) -> IdSchemeRead | None: ...
    def exists(self, scheme_id: int) -> bool: ...
    def get_by_code(self, code: str) -> IdSchemeRead | None: ...
    def list_all(self) -> list[IdSchemeRead]: ...
    def update(self, scheme_id: int, update: IdSchemeUpdateInternal) -> IdSchemeRead: ...


class InboxRepository(Protocol):
    def list_all(self, depth: int | None = None) -> list[InboxItem]: ...
    def delete(self, file: InboxDeleteRequest) -> None: ...
    def move(self, move: InboxImportRequest) -> tuple[Path, Path]: ...


class MetadataRepository(Protocol):
    """
    Protocol for managing metadata repositories.

    This interface defines the methods required to interact with a metadata repository.
    Implementations of this protocol provide functionalities to retrieve, update, and
    delete metadata associated with assets.

    """

    def get_asset_metadata(self, asset_id: int) -> list[MetadataRead]: ...
    def create(self, metadata: MetadataCreateInternal) -> MetadataRead: ...
    def get(self, metadata_id: int) -> MetadataRead | None: ...
    def update(self, metadata_id: int, update: MetadataUpdateInternal) -> MetadataRead: ...  # type: ignore
    def delete(self, metadata_id: int) -> None: ...


class JobRepository(Protocol):
    """
    Defines the contract for a job repository that manages job data operations.

    This class describes a protocol for interacting with a job repository. It serves
    as a blueprint for any concrete implementation, ensuring consistency in the method
    signatures for creating jobs, retrieving jobs, checking their existence, updating
    their status, and sending periodic heartbeat updates for active jobs.

    """

    def create(self, job_key: str) -> JobRead: ...
    def get(self, job_key: str) -> JobRead | None: ...
    def exists(self, job_key: str) -> bool: ...
    def heartbeat(self, job_key: str) -> JobRead: ...
    def mark_complete(self, job_key: str) -> JobRead: ...


class ExternalIdentifierRepository(Protocol):
    """
    Protocol for managing generic external identifiers for both assets and titles.

    This repository provides operations for attaching, resolving, and managing
    external IDs across multiple entity types using a typed association pattern.
    """

    def resolve(self, scheme_id: int, external_id: str) -> tuple[EntityTypeEnum, int] | None: ...
    def resolve_by_code(
        self, scheme_code: str, external_id: str
    ) -> tuple[EntityTypeEnum, int, int] | None: ...
    def get(self, record_id: int) -> ExternalIdentifierRead | None: ...
    def list_for_entity(
        self, entity_type: EntityTypeEnum, entity_id: int
    ) -> list[ExternalIdentifierReadExtended]: ...
    def create(self, ref: ExternalIdentifierCreateInternal) -> ExternalIdentifierRead: ...
    def update(
        self, record_id: int, update: ExternalIdentifierUpdateInternal
    ) -> ExternalIdentifierRead: ...
    def delete(self, record_id: int) -> None: ...


class ArtworkKindRepository(Protocol):
    """The artwork kinds an artwork can be categorised as.

    The same lookup-table shape as ``TitleTypeRepository``, for the same reason (#41).
    """

    def create(self, kind: ArtworkKindCreateInternal) -> ArtworkKindRead: ...
    def get(self, kind_id: int) -> ArtworkKindRead | None: ...
    def exists(self, kind_id: int) -> bool: ...
    def get_by_code(self, code: str) -> ArtworkKindRead | None: ...
    def list_all(self) -> list[ArtworkKindRead]: ...
    def update(
        self,
        kind_id: int,
        update: ArtworkKindUpdateInternal,  # type: ignore
    ) -> ArtworkKindRead: ...
    def delete(self, kind_id: int) -> None: ...
    def usage_count(self, kind_id: int) -> int: ...


class ArtworkRepository(Protocol):
    """Artwork belonging to a title or an asset, via the typed association pattern.

    ``entity_id`` has no foreign key -- its target table depends on ``entity_type``,
    which Postgres cannot express -- so the service layer owns that integrity check,
    exactly as it does for ``ExternalIdentifierRepository``.
    """

    def create(self, artwork: ArtworkCreateInternal) -> ArtworkRead: ...
    def get(self, artwork_id: int) -> ArtworkRead | None: ...
    def list_paged(
        self, params: ArtworkListParams, kind_id: int | None = None
    ) -> PaginatedResponse[ArtworkRead]: ...
    def list_for_entity(
        self, entity_type: EntityTypeEnum, entity_id: int, kind_id: int | None = None
    ) -> list[ArtworkRead]: ...
    def get_primary(
        self, entity_type: EntityTypeEnum, entity_id: int, kind_id: int
    ) -> ArtworkRead | None: ...
    def update(
        self,
        artwork_id: int,
        update: ArtworkUpdateInternal,  # type: ignore
    ) -> ArtworkRead: ...
    def set_primary(self, artwork_id: int) -> ArtworkRead: ...
    def delete(self, artwork_id: int) -> None: ...
    def count_for_entity(self, entity_type: EntityTypeEnum, entity_id: int) -> int: ...
    def resolve_for_titles(
        self, title_ids: Sequence[int], kind_ids: Sequence[int], max_depth: int = ...
    ) -> dict[int, ArtworkRead]: ...
